//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class AccountDetails
    {
        public Nullable<int> Id { get; set; }
        public Nullable<int> Name { get; set; }
        public Nullable<int> ClientName { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> AgreementName { get; set; }
        public Nullable<int> Request { get; set; }
        public Nullable<int> AccountDate { get; set; }
        public Nullable<int> PerformerName { get; set; }
        public Nullable<int> EmployeeName { get; set; }
        public Nullable<int> SignatoryFirst { get; set; }
        public Nullable<int> SignatorySecond { get; set; }
        public Nullable<int> ElectronicSignature { get; set; }
        public Nullable<int> ProtocolStatus { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<int> CreatorName { get; set; }
        public Nullable<int> ConfirmedName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> UpdatedOn { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
