//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class AccountList
    {
        public System.Guid Id { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocName { get; set; }
        public string ReportPeriod { get; set; }
        public Nullable<decimal> SummaWithNDS { get; set; }
        public Nullable<decimal> SummaNDS { get; set; }
        public string CurrencyName { get; set; }
        public string AgreementName { get; set; }
        public string ClaimName { get; set; }
        public string CustomerCompanyName { get; set; }
        public string PerformerCompanyName { get; set; }
        public string AgrManagerName { get; set; }
        public string Signer1Name { get; set; }
        public string Signer2Name { get; set; }
        public string TemplateName { get; set; }
        public string HasAttachmentImgPath { get; set; }
        public string HasAttachmentHint { get; set; }
        public string ApprovalAccountImgPath { get; set; }
        public string SigningAccountImgPath { get; set; }
        public string ApprovalClaimImgPath { get; set; }
        public string ApprovalProtocolImgPath { get; set; }
        public string SigningClaimImgPath { get; set; }
        public string SigningProtocolPath { get; set; }
        public string ApprovalAccountHint { get; set; }
        public string SigningAccountHint { get; set; }
        public string ApprovalClaimHint { get; set; }
        public string ApprovalProtocolHint { get; set; }
        public string SigningClaimHint { get; set; }
        public string SigningProtocolHint { get; set; }
    }
}
