//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class Act
    {
        public System.Guid Id { get; set; }
        public string TemplateName { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.Guid> DocStatusId { get; set; }
        public string DocStatusName { get; set; }
        public string DocName { get; set; }
        public Nullable<System.Guid> AgreementId { get; set; }
        public string AgreementName { get; set; }
        public Nullable<System.Guid> CustomerCompanyId { get; set; }
        public string CustomerCompanyLabel { get; set; }
        public string CustomerCompanyName { get; set; }
        public Nullable<System.Guid> PerformerCompanyId { get; set; }
        public string PerformerCompanyLabel { get; set; }
        public string PerformerCompanyName { get; set; }
        public Nullable<System.DateTime> DateBeg { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string RepoptPeriodName { get; set; }
        public Nullable<decimal> SummaWithNDS { get; set; }
        public Nullable<decimal> SummaNDS { get; set; }
        public string CurrencyName { get; set; }
        public string DocNote { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> IRSPerevozkiId { get; set; }
    }
}
