//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ActDetails
    {
        public Nullable<int> ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string NDS { get; set; }
        public decimal Summa { get; set; }
        public Nullable<decimal> SummaNDS { get; set; }
        public decimal SummaWithNDS { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<int> ConditionName { get; set; }
    }
}
