//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ActDetails
    {
        public Nullable<int> ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string NDS { get; set; }
        public decimal Summa { get; set; }
        public Nullable<decimal> SummaNDS { get; set; }
        public decimal SummaWithNDS { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<int> ConditionName { get; set; }
    }
}
