//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class AgreementList
    {
        public System.Guid Id { get; set; }
        public string DocNumber { get; set; }
        public string RegNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public decimal Balance { get; set; }
        public string DocName { get; set; }
        public Nullable<System.DateTime> DateBeg { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string CustomerCompanyName { get; set; }
        public string PerformerCompanyName { get; set; }
        public string AgrManagerName { get; set; }
        public string HasAttachmentImgPath { get; set; }
        public string HasAttachmentHint { get; set; }
        public string ApprovalPerformerImgPath { get; set; }
        public string ApprovalCustomerImgPath { get; set; }
        public string SigningPerformerImgPath { get; set; }
        public string SigningCustomerImgPath { get; set; }
        public string ApprovalPerformerHint { get; set; }
        public string ApprovalCustomerHint { get; set; }
        public string SigningPerformerHint { get; set; }
        public string SigningCustomerHint { get; set; }
        public string TemplateName { get; set; }
    }
}
