//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ClaimRouteDetails
    {
        public System.Guid RouteId { get; set; }
        public int Position { get; set; }
        public string CountryName { get; set; }
        public string StationInCode { get; set; }
        public string StationInName { get; set; }
        public string RailWayInName { get; set; }
        public string StationOutCode { get; set; }
        public string StationOutName { get; set; }
        public string RailWayOutName { get; set; }
        public int Distance { get; set; }
    }
}
