//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ClaimRollingStock
    {
        public string ContParkName { get; set; }
        public string ContKindName { get; set; }
        public string CarParkName { get; set; }
        public string CarKindName { get; set; }
        public string CarTypeName { get; set; }
        public string GroupTypeName { get; set; }
        public string ShipmentName { get; set; }
    }
}
