//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ClaimDetails
    {
        public System.Guid Id { get; set; }
        public string StatusName { get; set; }
        public string DocNumber { get; set; }
        public string RegNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocName { get; set; }
        public System.DateTime DateBeg { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string DatePeriod { get; set; }
        public System.Guid AgreementId { get; set; }
        public string AgreementName { get; set; }
        public Nullable<System.Guid> StFromId { get; set; }
        public string StFromCode6 { get; set; }
        public string StFromName { get; set; }
        public string RWFromName { get; set; }
        public Nullable<System.Guid> StToId { get; set; }
        public string StToCode6 { get; set; }
        public string StToName { get; set; }
        public string RWToName { get; set; }
        public int CarCount { get; set; }
        public decimal FrWeight { get; set; }
        public string FrETSNGCode { get; set; }
        public string FrETSNGName { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public string ContactFIO { get; set; }
        public string TelegrammList { get; set; }
        public Nullable<System.Guid> ApprovalPerformerImgId { get; set; }
        public Nullable<System.Guid> ApprovalCustomerImgId { get; set; }
        public Nullable<System.Guid> SigningPerformerImgId { get; set; }
        public Nullable<System.Guid> SigningCustomerImgId { get; set; }
        public Nullable<int> ApprovalPerformer { get; set; }
        public Nullable<int> ApprovalCustomer { get; set; }
        public Nullable<int> SigningPerformer { get; set; }
        public Nullable<int> SigningCustomer { get; set; }
    }
}
