//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ClaimLoadingSchedule
    {
        public Nullable<int> Version { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<decimal> FrWeight { get; set; }
        public Nullable<int> CarCount { get; set; }
    }
}
