//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class Claim
    {
        public System.Guid Id { get; set; }
        public string TemplateName { get; set; }
        public Guid? AgreementId { get; set; }
        public string AgreementName { get; set; }
        public Guid? CustomerCompanyId { get; set; }
        public string CustomerCompanyLabel { get; set; }
        public string CustomerCompanyName { get; set; }
        public Guid? PerformerCompanyId { get; set; }
        public string PerformerCompanyLabel { get; set; }
        public string PerformerCompanyName { get; set; }
        public string DocNumber { get; set; }
        public string RegNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public System.Guid DocStatusId { get; set; }
        public string DocStatusName { get; set; }
        public System.DateTime DateBeg { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string ReportPeriodName { get; set; }
        public string PlanType { get; set; }
        public string ClaimStatusName { get; set; }
        public string LoadingScheduleStatusName { get; set; }
        public Guid? ProtocolId { get; set; }
        public string ProtocolName { get; set; }
        public string ApprovalProtocolCustomerImgPath { get; set; }
        public string ApprovalProtocolPerformerImgPath { get; set; }
        public string SigningProtocolCustomerImgPath { get; set; }
        public string SigningProtocolPerformerImgPath { get; set; }
        public string ApprovalProtocolCustomerHint { get; set; }
        public string ApprovalProtocolPerformerHint { get; set; }
        public string SigningProtocolCustomerHint { get; set; }
        public string SigningProtocolPerformerHint { get; set; }
        public Guid? AccountId { get; set; }
        public string AccountName { get; set; }
        public string ApprovalAccountCustomerImgPath { get; set; }
        public string ApprovalAccountPerformerImgPath { get; set; }
        public string SigningAccountCustomerImgPath { get; set; }
        public string SigningAccountPerformerImgPath { get; set; }
        public string ApprovalAccountCustomerHint { get; set; }
        public string ApprovalAccountPerformerHint { get; set; }
        public string SigningAccountCustomerHint { get; set; }
        public string SigningAccountPerformerHint { get; set; }
        public Nullable<bool> ShowContInfo { get; set; }
        public string ContParkName { get; set; }
        public string ContKindName { get; set; }
        public string CarParkName { get; set; }
        public string CarKindName { get; set; }
        public string CarTypeName { get; set; }
        public string GroupTypeName { get; set; }
        public string ShipmentName { get; set; }
        public string CountryFromName { get; set; }
        public string CountryToName { get; set; }
        public Guid? StationFromId { get; set; }
        public string StationFromCode { get; set; }
        public string RailWayFromName { get; set; }
        public string StationFromName { get; set; }
        public Guid? StationToId { get; set; }
        public string StationToCode { get; set; }
        public string RailWayToName { get; set; }
        public string StationToName { get; set; }
        public string TransferTypeName { get; set; }
        public decimal Distance { get; set; }
        public int PeriodOfDelivery { get; set; }
        public string RouteName { get; set; }
        public string FrETSNGCode { get; set; }
        public string FrETSNGName { get; set; }
        public string FrGNGCode { get; set; }
        public string FrGNGName { get; set; }
        public string LoadFromTGNL { get; set; }
        public string LoadFromName { get; set; }
        public string LoadToTGNL { get; set; }
        public string LoadToName { get; set; }
        public decimal FrWeight { get; set; }
        public Nullable<int> ContCount { get; set; }
        public int CarCount { get; set; }
        public string ClaimNote { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> IRSPerevozkiId { get; set; }
    }
}
