//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ClaimRouteDetails
    {
        public System.Guid RouteId { get; set; }
        public int Position { get; set; }
        public string CountryName { get; set; }
        public string StationInCode { get; set; }
        public string StationInName { get; set; }
        public string RailWayInName { get; set; }
        public string StationOutCode { get; set; }
        public string StationOutName { get; set; }
        public string RailWayOutName { get; set; }
        public int Distance { get; set; }
    }
}
