//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ClaimLoadingSchedule
    {
        public Nullable<int> Version { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<decimal> FrWeight { get; set; }
        public Nullable<int> CarCount { get; set; }
    }
}
