//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ClaimList
    {
        public System.Guid Id { get; set; }
        public string StatusName { get; set; }
        public string DocNumber { get; set; }
        public string RegNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocName { get; set; }
        public System.DateTime DateBeg { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string AgreementName { get; set; }
        public string StFromCode6 { get; set; }
        public string StFromName { get; set; }
        public string RWFromName { get; set; }
        public string StToCode6 { get; set; }
        public string StToName { get; set; }
        public string RWToName { get; set; }
        public int CarCount { get; set; }
        public decimal FrWeight { get; set; }
        public string FrETSNGCode { get; set; }
        public string FrETSNGName { get; set; }
        public string ContactFIO { get; set; }
        public string TelegrammList { get; set; }
        public string HasAttachmentImgPath { get; set; }
        public string HasAttachmentHint { get; set; }
        public string ApprovalPerformerImgPath { get; set; }
        public string ApprovalCustomerImgPath { get; set; }
        public string SigningPerformerImgPath { get; set; }
        public string SigningCustomerImgPath { get; set; }
        public string ApprovalPerformerHint { get; set; }
        public string ApprovalCustomerHint { get; set; }
        public string SigningPerformerHint { get; set; }
        public string SigningCustomerHint { get; set; }
    }
}
