//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ClaimRollingStock
    {
        public string ContParkName { get; set; }
        public string ContKindName { get; set; }
        public string CarParkName { get; set; }
        public string CarKindName { get; set; }
        public string CarTypeName { get; set; }
        public string GroupTypeName { get; set; }
        public string ShipmentName { get; set; }
    }
}
