//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class Company
    {
        public System.Guid Id { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string ViewName { get; set; }
        public string Note { get; set; }
        public string CodeOKPO { get; set; }
        public string CodeINN { get; set; }
    }
}
