//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class Company
    {
        public System.Guid Id { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string ViewName { get; set; }
        public string Note { get; set; }
        public string CodeOKPO { get; set; }
        public string CodeINN { get; set; }
    }
}
