//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ContactDetails
    {
        public System.Guid Id { get; set; }
        public string F { get; set; }
        public string I { get; set; }
        public string O { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Guid? CompanyId { get; set; }
        public string CompanyName { get; set; }
    }
}
