//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class DocumentConditionList
    {
        public System.Guid Id { get; set; }
        public string MnemoCode { get; set; }
        public System.Guid ValueTypeId { get; set; }
        public string ValueTypeName { get; set; }
        public System.Guid ConditionGroupId { get; set; }
        public string ConditionGroupName { get; set; }
        public int PositionGroup { get; set; }
        public string ConditionName { get; set; }
    }
}
