//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class DocumentCondition
    {
        public int PositionGroup { get; set; }
        public int PositionValue { get; set; }
        public string Name { get; set; }
        public string ValueString { get; set; }
        public string ConditionLimitValue { get; set; }
        public System.Guid ConditionId { get; set; }
        public System.Guid ConditionGroupId { get; set; }
        public string ConditionGroupName { get; set; }
        public System.Guid ValueTypeId { get; set; }
        public string ValueTypeName { get; set; }
        public Nullable<int> ValueInteger { get; set; }
        public Nullable<double> ValueFloat { get; set; }
        public Nullable<decimal> ValueMoney { get; set; }
        public Nullable<System.Guid> ValueGUID { get; set; }
        public Nullable<System.DateTime> ValueDateTime { get; set; }
        public Nullable<double> ValueMIN { get; set; }
        public Nullable<double> ValueMAX { get; set; }
    }
}
