//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class DocumentConditionList
    {
        public System.Guid Id { get; set; }
        public string MnemoCode { get; set; }
        public System.Guid ValueTypeId { get; set; }
        public string ValueTypeName { get; set; }
        public System.Guid ConditionGroupId { get; set; }
        public string ConditionGroupName { get; set; }
        public int PositionGroup { get; set; }
        public string ConditionName { get; set; }
    }
}
