//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class InstructionList
    {
        public System.Guid Id { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocName { get; set; }
        public string AgreementName { get; set; }
        public string ClaimName { get; set; }
        public string CustomerCompanyName { get; set; }
        public string PerformerCompanyName { get; set; }
        public string AgrManagerName { get; set; }
        public string HasAttachmentImgPath { get; set; }
        public string HasAttachmentHint { get; set; }
        public string ApprovalInstructionHint { get; set; }
        public string SigningInstructionHint { get; set; }
        public string ApprovalInstructionImgPath { get; set; }
        public string SingingInstructionImgPath { get; set; }
        public string TemplateName { get; set; }
    }
}
