//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class Protocol
    {
        public System.Guid Id { get; set; }
        public string TemplateName { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Guid? DocStatusId { get; set; }
        public string DocStatusName { get; set; }
        public string DocName { get; set; }
        public Guid? AgreementId { get; set; }
        public string AgreementName { get; set; }
        public Guid? CustomerCompanyId { get; set; }
        public string CustomerCompanyLabel { get; set; }
        public string CustomerCompanyName { get; set; }
        public Guid? PerformerCompanyId { get; set; }
        public string PerformerCompanyLabel { get; set; }
        public string PerformerCompanyName { get; set; }
        public Nullable<System.DateTime> DateBeg { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DateStop { get; set; }
        public Guid? ClaimId { get; set; }
        public string ClaimName { get; set; }
        public string DocNote { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> IRSPerevozkiId { get; set; }
    }
}
