//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ProtocolList
    {
        public System.Guid Id { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocName { get; set; }
        public Nullable<System.DateTime> DateBeg { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string AgreementName { get; set; }
        public string ClaimName { get; set; }
        public string CustomerCompanyName { get; set; }
        public string PerformerCompanyName { get; set; }
        public string AgrManagerName { get; set; }
        public string TemplateName { get; set; }
        public string HasAttachmentImgPath { get; set; }
        public string HasAttachmentHint { get; set; }
        public string ApprovalPerformerImgPath { get; set; }
        public string ApprovalCustomerImgPath { get; set; }
        public string SigningPerformerImgPath { get; set; }
        public string SigningCustomerImgPath { get; set; }
        public string ApprovalPerformerHint { get; set; }
        public string ApprovalCustomerHint { get; set; }
        public string SigningPerformerHint { get; set; }
        public string SigningCustomerHint { get; set; }
    }
}
