//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ProtocolDetails
    {
        public System.Guid ServiceId { get; set; }
        public string ServiceName { get; set; }
        public string MeasureName { get; set; }
        public string NDS { get; set; }
        public decimal Summa { get; set; }
        public decimal SummaNDS { get; set; }
        public decimal SummaWithNDS { get; set; }
        public string CurrencyName { get; set; }
        public string CountryName { get; set; }
        public string StationFromName { get; set; }
        public string StationToName { get; set; }
        public string FreightName { get; set; }
        public string GroupTypeName { get; set; }
        public string CarParkName { get; set; }
    }
}
