//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class ReceivedMailList
    {
        public System.Guid EmailId { get; set; }
        public string SenderName { get; set; }
        public string Subject { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string StatusName { get; set; }
        public System.DateTime ViewedAt { get; set; }
        public string ViewerName { get; set; }
    }
}
