//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class UserNotificationList
    {
        public System.Guid Id { get; set; }
        public Guid? UserFromId { get; set; }
        public Guid? UserToID { get; set; }
        public string UserFromName { get; set; }
        public string UserToName { get; set; }
        public Guid? CompanyFromId { get; set; }
        public Guid? CompanyToId { get; set; }
        public string CompanyFromName { get; set; }
        public string CompanyToName { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ViewDate { get; set; }
        public Guid? ObjectId { get; set; }
    }
}
