//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class UserDetailsList
    {
        public System.Guid CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNote { get; set; }
        public string CodeOKPO { get; set; }
        public string CodeINN { get; set; }
    }
}
