//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class UserMail
    {
        public System.Guid SenderUserId { get; set; }
        public string SenderContactName { get; set; }
        public string SenderCompanyName { get; set; }
        public System.Guid ReceiverCompanyId { get; set; }
        public string ReceiverCompanyName { get; set; }
        public System.DateTime ViewedAt { get; set; }
        public Nullable<System.Guid> ViewerId { get; set; }
        public string ViewerName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public string StatusName { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
