//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class UserMail
    {
        public System.Guid SenderUserId { get; set; }
        public string SenderContactName { get; set; }
        public string SenderCompanyName { get; set; }
        public System.Guid ReceiverCompanyId { get; set; }
        public string ReceiverCompanyName { get; set; }
        public System.DateTime ViewedAt { get; set; }
        public Guid? ViewerId { get; set; }
        public string ViewerName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Guid? StatusId { get; set; }
        public string StatusName { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
