//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class UserList
    {
        public System.Guid UserId { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
    }
}
