//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class UserDetailsList
    {
        public System.Guid CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNote { get; set; }
        public string CodeOKPO { get; set; }
        public string CodeINN { get; set; }
    }
}
