//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASUVP.Core.DataAccess.Model
{
    using System;
    
    public partial class UserMailReceivedList
    {
        public System.Guid Id { get; set; }
        public string SenderName { get; set; }
        public string Subject { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string StatusName { get; set; }
    }
}
