//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26.01.2017 14:00:57
namespace ASUVP.Online.OData.Models
{
    /// <summary>
    /// There are no comments for UserODataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("UserODataSingle")]
    public partial class UserODataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<UserOData>
    {
        /// <summary>
        /// Initialize a new UserODataSingle object.
        /// </summary>
        public UserODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new UserODataSingle object.
        /// </summary>
        public UserODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new UserODataSingle object.
        /// </summary>
        public UserODataSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<UserOData> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for UserOData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("UserOData")]
    public partial class UserOData : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new UserOData object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static UserOData CreateUserOData(global::System.Guid ID)
        {
            UserOData userOData = new UserOData();
            userOData.Id = ID;
            return userOData;
        }
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserName")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FirstName")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property MiddleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MiddleName")]
        public string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this.OnMiddleNameChanging(value);
                this._MiddleName = value;
                this.OnMiddleNameChanged();
                this.OnPropertyChanged("MiddleName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _MiddleName;
        partial void OnMiddleNameChanging(string value);
        partial void OnMiddleNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastName")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RoleODataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RoleODataSingle")]
    public partial class RoleODataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RoleOData>
    {
        /// <summary>
        /// Initialize a new RoleODataSingle object.
        /// </summary>
        public RoleODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RoleODataSingle object.
        /// </summary>
        public RoleODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RoleODataSingle object.
        /// </summary>
        public RoleODataSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RoleOData> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Permissions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Permissions")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.PermissionOData> Permissions
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Permissions == null))
                {
                    this._Permissions = Context.CreateQuery<global::ASUVP.Online.OData.Models.PermissionOData>(GetPath("Permissions"));
                }
                return this._Permissions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.PermissionOData> _Permissions;
    }
    /// <summary>
    /// There are no comments for RoleOData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("RoleOData")]
    public partial class RoleOData : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RoleOData object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static RoleOData CreateRoleOData(global::System.Guid ID)
        {
            RoleOData roleOData = new RoleOData();
            roleOData.Id = ID;
            return roleOData;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Permissions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Permissions")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ASUVP.Online.OData.Models.PermissionOData> Permissions
        {
            get
            {
                return this._Permissions;
            }
            set
            {
                this.OnPermissionsChanging(value);
                this._Permissions = value;
                this.OnPermissionsChanged();
                this.OnPropertyChanged("Permissions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ASUVP.Online.OData.Models.PermissionOData> _Permissions = new global::Microsoft.OData.Client.DataServiceCollection<global::ASUVP.Online.OData.Models.PermissionOData>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnPermissionsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ASUVP.Online.OData.Models.PermissionOData> value);
        partial void OnPermissionsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PermissionODataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PermissionODataSingle")]
    public partial class PermissionODataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PermissionOData>
    {
        /// <summary>
        /// Initialize a new PermissionODataSingle object.
        /// </summary>
        public PermissionODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PermissionODataSingle object.
        /// </summary>
        public PermissionODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PermissionODataSingle object.
        /// </summary>
        public PermissionODataSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PermissionOData> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PermissionOData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PermissionOData")]
    public partial class PermissionOData : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PermissionOData object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static PermissionOData CreatePermissionOData(global::System.Guid ID)
        {
            PermissionOData permissionOData = new PermissionOData();
            permissionOData.Id = ID;
            return permissionOData;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Code")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Code2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Code2")]
        public string Code2
        {
            get
            {
                return this._Code2;
            }
            set
            {
                this.OnCode2Changing(value);
                this._Code2 = value;
                this.OnCode2Changed();
                this.OnPropertyChanged("Code2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Code2;
        partial void OnCode2Changing(string value);
        partial void OnCode2Changed();
        /// <summary>
        /// There are no comments for Property Module in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Module")]
        public string Module
        {
            get
            {
                return this._Module;
            }
            set
            {
                this.OnModuleChanging(value);
                this._Module = value;
                this.OnModuleChanged();
                this.OnPropertyChanged("Module");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Module;
        partial void OnModuleChanging(string value);
        partial void OnModuleChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AgreementODataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AgreementODataSingle")]
    public partial class AgreementODataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<AgreementOData>
    {
        /// <summary>
        /// Initialize a new AgreementODataSingle object.
        /// </summary>
        public AgreementODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AgreementODataSingle object.
        /// </summary>
        public AgreementODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AgreementODataSingle object.
        /// </summary>
        public AgreementODataSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<AgreementOData> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for AgreementOData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("AgreementOData")]
    public partial class AgreementOData : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AgreementOData object.
        /// </summary>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="endDate">Initial value of EndDate.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static AgreementOData CreateAgreementOData(global::System.DateTimeOffset date, global::System.DateTimeOffset startDate, global::System.DateTimeOffset endDate, global::System.Guid ID)
        {
            AgreementOData agreementOData = new AgreementOData();
            agreementOData.Date = date;
            agreementOData.StartDate = startDate;
            agreementOData.EndDate = endDate;
            agreementOData.Id = ID;
            return agreementOData;
        }
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Number")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Date")]
        public global::System.DateTimeOffset Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _Date;
        partial void OnDateChanging(global::System.DateTimeOffset value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("StartDate")]
        public global::System.DateTimeOffset StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this._StartDate = value;
                this.OnStartDateChanged();
                this.OnPropertyChanged("StartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _StartDate;
        partial void OnStartDateChanging(global::System.DateTimeOffset value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EndDate")]
        public global::System.DateTimeOffset EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this._EndDate = value;
                this.OnEndDateChanged();
                this.OnPropertyChanged("EndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _EndDate;
        partial void OnEndDateChanging(global::System.DateTimeOffset value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Property CustomerCompany in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomerCompany")]
        public string CustomerCompany
        {
            get
            {
                return this._CustomerCompany;
            }
            set
            {
                this.OnCustomerCompanyChanging(value);
                this._CustomerCompany = value;
                this.OnCustomerCompanyChanged();
                this.OnPropertyChanged("CustomerCompany");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _CustomerCompany;
        partial void OnCustomerCompanyChanging(string value);
        partial void OnCustomerCompanyChanged();
        /// <summary>
        /// There are no comments for Property CustomerCompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomerCompanyId")]
        public global::System.Nullable<global::System.Guid> CustomerCompanyId
        {
            get
            {
                return this._CustomerCompanyId;
            }
            set
            {
                this.OnCustomerCompanyIdChanging(value);
                this._CustomerCompanyId = value;
                this.OnCustomerCompanyIdChanged();
                this.OnPropertyChanged("CustomerCompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _CustomerCompanyId;
        partial void OnCustomerCompanyIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCustomerCompanyIdChanged();
        /// <summary>
        /// There are no comments for Property TargetCompany in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TargetCompany")]
        public string TargetCompany
        {
            get
            {
                return this._TargetCompany;
            }
            set
            {
                this.OnTargetCompanyChanging(value);
                this._TargetCompany = value;
                this.OnTargetCompanyChanged();
                this.OnPropertyChanged("TargetCompany");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _TargetCompany;
        partial void OnTargetCompanyChanging(string value);
        partial void OnTargetCompanyChanged();
        /// <summary>
        /// There are no comments for Property TargetCompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TargetCompanyId")]
        public global::System.Nullable<global::System.Guid> TargetCompanyId
        {
            get
            {
                return this._TargetCompanyId;
            }
            set
            {
                this.OnTargetCompanyIdChanging(value);
                this._TargetCompanyId = value;
                this.OnTargetCompanyIdChanged();
                this.OnPropertyChanged("TargetCompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _TargetCompanyId;
        partial void OnTargetCompanyIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnTargetCompanyIdChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ContactODataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ContactODataSingle")]
    public partial class ContactODataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ContactOData>
    {
        /// <summary>
        /// Initialize a new ContactODataSingle object.
        /// </summary>
        public ContactODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ContactODataSingle object.
        /// </summary>
        public ContactODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ContactODataSingle object.
        /// </summary>
        public ContactODataSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ContactOData> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ContactOData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ContactOData")]
    public partial class ContactOData : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ContactOData object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ContactOData CreateContactOData(global::System.Guid ID)
        {
            ContactOData contactOData = new ContactOData();
            contactOData.Id = ID;
            return contactOData;
        }
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FirstName")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property MiddleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MiddleName")]
        public string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this.OnMiddleNameChanging(value);
                this._MiddleName = value;
                this.OnMiddleNameChanged();
                this.OnPropertyChanged("MiddleName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _MiddleName;
        partial void OnMiddleNameChanging(string value);
        partial void OnMiddleNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastName")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Phone")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property CompanyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyName")]
        public string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this.OnCompanyNameChanging(value);
                this._CompanyName = value;
                this.OnCompanyNameChanged();
                this.OnPropertyChanged("CompanyName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _CompanyName;
        partial void OnCompanyNameChanging(string value);
        partial void OnCompanyNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CompanyODataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyODataSingle")]
    public partial class CompanyODataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CompanyOData>
    {
        /// <summary>
        /// Initialize a new CompanyODataSingle object.
        /// </summary>
        public CompanyODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CompanyODataSingle object.
        /// </summary>
        public CompanyODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CompanyODataSingle object.
        /// </summary>
        public CompanyODataSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CompanyOData> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for CompanyOData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyOData")]
    public partial class CompanyOData : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CompanyOData object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static CompanyOData CreateCompanyOData(global::System.Guid ID)
        {
            CompanyOData companyOData = new CompanyOData();
            companyOData.Id = ID;
            return companyOData;
        }
        /// <summary>
        /// There are no comments for Property ShortName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShortName")]
        public string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                this.OnShortNameChanging(value);
                this._ShortName = value;
                this.OnShortNameChanged();
                this.OnPropertyChanged("ShortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ShortName;
        partial void OnShortNameChanging(string value);
        partial void OnShortNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for EmployeeODataSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EmployeeODataSingle")]
    public partial class EmployeeODataSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<EmployeeOData>
    {
        /// <summary>
        /// Initialize a new EmployeeODataSingle object.
        /// </summary>
        public EmployeeODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new EmployeeODataSingle object.
        /// </summary>
        public EmployeeODataSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new EmployeeODataSingle object.
        /// </summary>
        public EmployeeODataSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<EmployeeOData> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Roles")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.RoleOData> Roles
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Roles == null))
                {
                    this._Roles = Context.CreateQuery<global::ASUVP.Online.OData.Models.RoleOData>(GetPath("Roles"));
                }
                return this._Roles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.RoleOData> _Roles;
    }
    /// <summary>
    /// There are no comments for EmployeeOData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("EmployeeOData")]
    public partial class EmployeeOData : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EmployeeOData object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="companyId">Initial value of CompanyId.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static EmployeeOData CreateEmployeeOData(global::System.Guid userId, global::System.Guid companyId, global::System.Guid ID)
        {
            EmployeeOData employeeOData = new EmployeeOData();
            employeeOData.UserId = userId;
            employeeOData.CompanyId = companyId;
            employeeOData.Id = ID;
            return employeeOData;
        }
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserId")]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property CompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyId")]
        public global::System.Guid CompanyId
        {
            get
            {
                return this._CompanyId;
            }
            set
            {
                this.OnCompanyIdChanging(value);
                this._CompanyId = value;
                this.OnCompanyIdChanged();
                this.OnPropertyChanged("CompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _CompanyId;
        partial void OnCompanyIdChanging(global::System.Guid value);
        partial void OnCompanyIdChanged();
        /// <summary>
        /// There are no comments for Property ShortName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShortName")]
        public string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                this.OnShortNameChanging(value);
                this._ShortName = value;
                this.OnShortNameChanged();
                this.OnPropertyChanged("ShortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _ShortName;
        partial void OnShortNameChanging(string value);
        partial void OnShortNameChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Note")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Roles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Roles")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ASUVP.Online.OData.Models.RoleOData> Roles
        {
            get
            {
                return this._Roles;
            }
            set
            {
                this.OnRolesChanging(value);
                this._Roles = value;
                this.OnRolesChanged();
                this.OnPropertyChanged("Roles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ASUVP.Online.OData.Models.RoleOData> _Roles = new global::Microsoft.OData.Client.DataServiceCollection<global::ASUVP.Online.OData.Models.RoleOData>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRolesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ASUVP.Online.OData.Models.RoleOData> value);
        partial void OnRolesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.UserOData as global::ASUVP.Online.OData.Models.UserODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ASUVP.Online.OData.Models.UserODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.UserOData> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ASUVP.Online.OData.Models.UserODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.UserOData as global::ASUVP.Online.OData.Models.UserODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ASUVP.Online.OData.Models.UserODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.UserOData> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ASUVP.Online.OData.Models.UserODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.RoleOData as global::ASUVP.Online.OData.Models.RoleODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ASUVP.Online.OData.Models.RoleODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.RoleOData> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ASUVP.Online.OData.Models.RoleODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.RoleOData as global::ASUVP.Online.OData.Models.RoleODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ASUVP.Online.OData.Models.RoleODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.RoleOData> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ASUVP.Online.OData.Models.RoleODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.PermissionOData as global::ASUVP.Online.OData.Models.PermissionODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ASUVP.Online.OData.Models.PermissionODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.PermissionOData> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ASUVP.Online.OData.Models.PermissionODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.PermissionOData as global::ASUVP.Online.OData.Models.PermissionODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ASUVP.Online.OData.Models.PermissionODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.PermissionOData> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ASUVP.Online.OData.Models.PermissionODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.AgreementOData as global::ASUVP.Online.OData.Models.AgreementODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ASUVP.Online.OData.Models.AgreementODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.AgreementOData> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ASUVP.Online.OData.Models.AgreementODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.AgreementOData as global::ASUVP.Online.OData.Models.AgreementODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ASUVP.Online.OData.Models.AgreementODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.AgreementOData> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ASUVP.Online.OData.Models.AgreementODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.ContactOData as global::ASUVP.Online.OData.Models.ContactODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ASUVP.Online.OData.Models.ContactODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.ContactOData> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ASUVP.Online.OData.Models.ContactODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.ContactOData as global::ASUVP.Online.OData.Models.ContactODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ASUVP.Online.OData.Models.ContactODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.ContactOData> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ASUVP.Online.OData.Models.ContactODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.CompanyOData as global::ASUVP.Online.OData.Models.CompanyODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ASUVP.Online.OData.Models.CompanyODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.CompanyOData> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ASUVP.Online.OData.Models.CompanyODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.CompanyOData as global::ASUVP.Online.OData.Models.CompanyODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ASUVP.Online.OData.Models.CompanyODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.CompanyOData> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ASUVP.Online.OData.Models.CompanyODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.EmployeeOData as global::ASUVP.Online.OData.Models.EmployeeODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ASUVP.Online.OData.Models.EmployeeODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.EmployeeOData> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ASUVP.Online.OData.Models.EmployeeODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ASUVP.Online.OData.Models.EmployeeOData as global::ASUVP.Online.OData.Models.EmployeeODataSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ASUVP.Online.OData.Models.EmployeeODataSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.EmployeeOData> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ASUVP.Online.OData.Models.EmployeeODataSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace ASUVP.Online.OData
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "OData.Models", "ASUVP.Online.OData.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "OData", "ASUVP.Online.OData");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("ASUVP.Online.OData.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("OData.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("OData.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ASUVP.Online.OData", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("OData.", originalNameAttribute.OriginalName);
                }
                return string.Concat("OData.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for UserOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserOData")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.UserOData> UserOData
        {
            get
            {
                if ((this._UserOData == null))
                {
                    this._UserOData = base.CreateQuery<global::ASUVP.Online.OData.Models.UserOData>("UserOData");
                }
                return this._UserOData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.UserOData> _UserOData;
        /// <summary>
        /// There are no comments for RoleOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RoleOData")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.RoleOData> RoleOData
        {
            get
            {
                if ((this._RoleOData == null))
                {
                    this._RoleOData = base.CreateQuery<global::ASUVP.Online.OData.Models.RoleOData>("RoleOData");
                }
                return this._RoleOData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.RoleOData> _RoleOData;
        /// <summary>
        /// There are no comments for PermissionOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PermissionOData")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.PermissionOData> PermissionOData
        {
            get
            {
                if ((this._PermissionOData == null))
                {
                    this._PermissionOData = base.CreateQuery<global::ASUVP.Online.OData.Models.PermissionOData>("PermissionOData");
                }
                return this._PermissionOData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.PermissionOData> _PermissionOData;
        /// <summary>
        /// There are no comments for AgreementOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AgreementOData")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.AgreementOData> AgreementOData
        {
            get
            {
                if ((this._AgreementOData == null))
                {
                    this._AgreementOData = base.CreateQuery<global::ASUVP.Online.OData.Models.AgreementOData>("AgreementOData");
                }
                return this._AgreementOData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.AgreementOData> _AgreementOData;
        /// <summary>
        /// There are no comments for ContactOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ContactOData")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.ContactOData> ContactOData
        {
            get
            {
                if ((this._ContactOData == null))
                {
                    this._ContactOData = base.CreateQuery<global::ASUVP.Online.OData.Models.ContactOData>("ContactOData");
                }
                return this._ContactOData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.ContactOData> _ContactOData;
        /// <summary>
        /// There are no comments for CompanyOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyOData")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.CompanyOData> CompanyOData
        {
            get
            {
                if ((this._CompanyOData == null))
                {
                    this._CompanyOData = base.CreateQuery<global::ASUVP.Online.OData.Models.CompanyOData>("CompanyOData");
                }
                return this._CompanyOData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.CompanyOData> _CompanyOData;
        /// <summary>
        /// There are no comments for EmployeeOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EmployeeOData")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.EmployeeOData> EmployeeOData
        {
            get
            {
                if ((this._EmployeeOData == null))
                {
                    this._EmployeeOData = base.CreateQuery<global::ASUVP.Online.OData.Models.EmployeeOData>("EmployeeOData");
                }
                return this._EmployeeOData;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ASUVP.Online.OData.Models.EmployeeOData> _EmployeeOData;
        /// <summary>
        /// There are no comments for UserOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToUserOData(global::ASUVP.Online.OData.Models.UserOData userOData)
        {
            base.AddObject("UserOData", userOData);
        }
        /// <summary>
        /// There are no comments for RoleOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToRoleOData(global::ASUVP.Online.OData.Models.RoleOData roleOData)
        {
            base.AddObject("RoleOData", roleOData);
        }
        /// <summary>
        /// There are no comments for PermissionOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToPermissionOData(global::ASUVP.Online.OData.Models.PermissionOData permissionOData)
        {
            base.AddObject("PermissionOData", permissionOData);
        }
        /// <summary>
        /// There are no comments for AgreementOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToAgreementOData(global::ASUVP.Online.OData.Models.AgreementOData agreementOData)
        {
            base.AddObject("AgreementOData", agreementOData);
        }
        /// <summary>
        /// There are no comments for ContactOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToContactOData(global::ASUVP.Online.OData.Models.ContactOData contactOData)
        {
            base.AddObject("ContactOData", contactOData);
        }
        /// <summary>
        /// There are no comments for CompanyOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCompanyOData(global::ASUVP.Online.OData.Models.CompanyOData companyOData)
        {
            base.AddObject("CompanyOData", companyOData);
        }
        /// <summary>
        /// There are no comments for EmployeeOData in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToEmployeeOData(global::ASUVP.Online.OData.Models.EmployeeOData employeeOData)
        {
            base.AddObject("EmployeeOData", employeeOData);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""OData.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""UserOData"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""UserName"" Type=""Edm.String"" />
        <Property Name=""FirstName"" Type=""Edm.String"" />
        <Property Name=""MiddleName"" Type=""Edm.String"" />
        <Property Name=""LastName"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""RoleOData"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <NavigationProperty Name=""Permissions"" Type=""Collection(OData.Models.PermissionOData)"" />
      </EntityType>
      <EntityType Name=""PermissionOData"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Code"" Type=""Edm.String"" />
        <Property Name=""Code2"" Type=""Edm.String"" />
        <Property Name=""Module"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""AgreementOData"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Number"" Type=""Edm.String"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Date"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""StartDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""EndDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""CustomerCompany"" Type=""Edm.String"" />
        <Property Name=""CustomerCompanyId"" Type=""Edm.Guid"" />
        <Property Name=""TargetCompany"" Type=""Edm.String"" />
        <Property Name=""TargetCompanyId"" Type=""Edm.Guid"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""ContactOData"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""FirstName"" Type=""Edm.String"" />
        <Property Name=""MiddleName"" Type=""Edm.String"" />
        <Property Name=""LastName"" Type=""Edm.String"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""Phone"" Type=""Edm.String"" />
        <Property Name=""CompanyName"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""CompanyOData"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""ShortName"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""EmployeeOData"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""UserId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""CompanyId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""ShortName"" Type=""Edm.String"" />
        <Property Name=""Note"" Type=""Edm.String"" />
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <NavigationProperty Name=""Roles"" Type=""Collection(OData.Models.RoleOData)"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""OData"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""UserOData"" EntityType=""OData.Models.UserOData"" />
        <EntitySet Name=""RoleOData"" EntityType=""OData.Models.RoleOData"">
          <NavigationPropertyBinding Path=""Permissions"" Target=""PermissionOData"" />
        </EntitySet>
        <EntitySet Name=""PermissionOData"" EntityType=""OData.Models.PermissionOData"" />
        <EntitySet Name=""AgreementOData"" EntityType=""OData.Models.AgreementOData"" />
        <EntitySet Name=""ContactOData"" EntityType=""OData.Models.ContactOData"" />
        <EntitySet Name=""CompanyOData"" EntityType=""OData.Models.CompanyOData"" />
        <EntitySet Name=""EmployeeOData"" EntityType=""OData.Models.EmployeeOData"">
          <NavigationPropertyBinding Path=""Roles"" Target=""RoleOData"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
